version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
      FLASK_APP: your_app.py
      SECRET_KEY: 1234@1234mR  # Change this to a more secure secret key
